#!/usr/bin/env python3
"""
Task 4: Research Notebook Writer
自动维护阶段报告
"""

import argparse
import json
from datetime import datetime
from pathlib import Path

class NotebookWriter:
    """自动研究笔记生成器"""
    
    def __init__(self):
        self.reports_dir = Path(__file__).parent.parent / "reports"
        self.reports_dir.mkdir(exist_ok=True)
        self.results_dir = Path(__file__).parent.parent / "results"
    
    def write_weekly_report(self, output_file: str = None) -> str:
        """生成周度收敛报告"""
        
        # 读取所有结果
        results = self._load_all_results()
        
        # 生成报告
        report = self._generate_report(results)
        
        # 保存
        if not output_file:
            output_file = self.reports_dir / f"weekly_convergence_{datetime.now():%Y%W}.md"
        else:
            output_file = self.reports_dir / output_file
        
        with open(output_file, 'w') as f:
            f.write(report)
        
        print(f"📝 Report written: {output_file}")
        return str(output_file)
    
    def _load_all_results(self) -> list:
        """加载所有结果文件"""
        results = []
        
        for result_file in self.results_dir.glob("*.json"):
            try:
                with open(result_file) as f:
                    data = json.load(f)
                    data["_source_file"] = result_file.name
                    results.append(data)
            except:
                pass
        
        return sorted(results, key=lambda x: x.get("timestamp", ""), reverse=True)
    
    def _generate_report(self, results: list) -> str:
        """生成 Markdown 报告"""
        
        # 按假设分组
        by_hypothesis = {}
        for r in results:
            hyp = r.get("hypothesis", "unknown")
            if hyp not in by_hypothesis:
                by_hypothesis[hyp] = []
            by_hypothesis[hyp].append(r)
        
        report = f"""# SOCS Weekly Convergence Report

**Generated**: {datetime.now().isoformat()}  
**Autoresearch Operator**: Active

---

## Executive Summary

"""
        
        # 找出 top candidate
        if results:
            best = max(results, key=lambda r: r.get("metrics", {}).get("cwci", 0))
            report += f"""
- **Current Top Candidate**: {best['hypothesis']} ({best['gate']})
- **Best CWCI**: {best['metrics'].get('cwci', 0):.3f}
- **Status**: {best['verdict']}

"""
        
        # 各假设状态
        report += "## Hypothesis Status\n\n"
        report += "| Hypothesis | Gate | Verdict | CWCI | Notes |\n"
        report += "|-----------|------|---------|------|-------|\n"
        
        for hyp, hyp_results in by_hypothesis.items():
            for r in hyp_results[:3]:  # 最近3个结果
                report += f"| {hyp} | {r['gate']} | {r['verdict']} | {r.get('metrics', {}).get('cwci', 0):.3f} | Auto-run |\n"
        
        report += "\n## Recent Results\n\n"
        
        for r in results[:5]:
            report += f"""### {r['hypothesis']} {r['gate']}
- **Timestamp**: {r['timestamp']}
- **Verdict**: {r['verdict']}
- **Metrics**: {json.dumps(r.get('metrics', {}), indent=2)}

"""
        
        report += """## Next Actions (Auto-Generated)

"""
        
        # 生成建议
        if "O1" in by_hypothesis:
            o1_results = by_hypothesis["O1"]
            if any(r["verdict"] == "PASSED" and r["gate"] == "Gate_2" for r in o1_results):
                report += "- [ ] **O1**: Proceed to open-world smoke test\n"
        
        if "OQS" in by_hypothesis:
            oqs_results = by_hypothesis["OQS"]
            if any(r["verdict"] == "PARTIAL" and r["gate"] == "Gate_1" for r in oqs_results):
                report += "- [ ] **OQS**: Apply minimal corrections, run Gate 1.5\n"
        
        report += """
## Limitations

- All results are SIMULATION-LIMITED until real SOCS integration
- Hazard/energy/prediction metrics are simulated approximations
- Conclusions should not be extrapolated to operational readiness

---

*This report was auto-generated by SOCS Autoresearch Operator*  
*Human review required before architecture decisions*
"""
        
        return report

def main():
    parser = argparse.ArgumentParser(description="Notebook Writer")
    parser.add_argument("--output", help="Output file name")
    
    args = parser.parse_args()
    
    writer = NotebookWriter()
    report_path = writer.write_weekly_report(args.output)
    
    print(f"\n✅ Report generated: {report_path}")

if __name__ == "__main__":
    main()
